server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ycx3430476/aispringcloud.git
          searchPaths: config
          username: 792433422@qq.com
          password: ycx13088939861.
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/